spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ruiji?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      password: 123456
      username: root

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印
    map-underscore-to-camel-case: true  #作用name_id 可以转换成 nameId
  type-aliases-package: com.tyl.mybatisplus.pojo   #取别名 是指在xml中的别名
  mapper-locations: classpath:mapper/*.xml   #配置xml文件是 ，文件放置的地方
  global-config:
    db-config:
      id-type: assign_id  #表中未设自增 采用这个配置可以按照雪花算法自动生成id



